name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ci-cd-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Update Helm values in GitOps repo
        run: |
          git clone https://${{ secrets.GITOPS_TOKEN }}@github.com/leopincle/gitops-helm-argocd.git
          cd gitops-helm-argocd/helm/ci-cd-app/

          echo "BEFORE:"
          cat values.yaml

          # Update tag correctamente
          sed -i "s/tag:.*/tag: \"${{ env.IMAGE_TAG }}\"/" values.yaml

          echo "AFTER:"
          cat values.yaml

          # Config git
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add values.yaml

          git commit -m "chore(image): update tag to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"

          git push