name: Promote Image Between Environments

on:
  workflow_dispatch:
    inputs:
      source_env:
        description: "Source environment"
        required: true
        type: choice
        options:
          - dev
          - staging

      target_env:
        description: "Target environment"
        required: true
        type: choice
        options:
          - staging
          - prod

jobs:
  promote:
    runs-on: ubuntu-latest

    # ENVIRONMENT = CONTROL DE APPROVALS
    environment: ${{ inputs.target_env }}

    steps:
      - name: Checkout CI repo
        uses: actions/checkout@v4

      - name: Clone GitOps repository
        run: |
          git clone https://${{ secrets.GITOPS_TOKEN }}@github.com/leopincle/gitops-helm-argocd.git

      - name: Extract image tag from source environment
        id: extract_tag
        run: |
          cd gitops-helm-argocd/helm/ci-cd-app

          TAG=$(grep 'tag:' values-${{ inputs.source_env }}.yaml | awk '{print $2}')
          echo "TAG=$TAG" >> $GITHUB_ENV

          echo "Extracted TAG=$TAG"

      - name: Validate promotion flow
        run: |
          if [[ "${{ inputs.source_env }}" == "dev" && "${{ inputs.target_env }}" == "prod" ]]; then
            echo "Direct promotion from dev to prod is not allowed"
            exit 1
          fi

      - name: Promote image to target environment
        run: |
          cd gitops-helm-argocd/helm/ci-cd-app

          echo "Updating values-${{ inputs.target_env }}.yaml with tag $TAG"

          sed -i "s/tag:.*/tag: ${TAG}/" values-${{ inputs.target_env }}.yaml

          echo "Result:"
          cat values-${{ inputs.target_env }}.yaml

      - name: Commit & push changes
        run: |
          cd gitops-helm-argocd

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "feat(promotion): promote ${TAG} from ${{ inputs.source_env }} to ${{ inputs.target_env }}"

          git push